
const rawTsvData = `1	La batalla de Stalingrado, librada entre agosto de 1942 y febrero de 1943, representa el enfrentamiento más sangriento en la historia de la humanidad y el punto de inflexión decisivo de la Segunda Guerra Mundial en Europa.	1	The Battle of Stalingrad, fought between August 1942 and February 1943, represents the bloodiest confrontation in human history and the decisive turning point of World War II in Europe.
2	El conflicto comenzó cuando el ejército alemán lanzó una ofensiva masiva hacia la ciudad de Stalingrado, un centro industrial estratégico que llevaba el nombre del líder soviético Iósif Stalin.	1	The conflict began when the German army launched a massive offensive toward the city of Stalingrad, a strategic industrial hub that bore the name of the Soviet leader Joseph Stalin.
3	Adolf Hitler buscaba capturar la urbe para asegurar el flanco de sus tropas que avanzaban hacia los ricos campos petrolíferos del Cáucaso y para cortar las rutas de transporte fundamentales de la Unión Soviética a lo largo del río Volga.	1	Adolf Hitler sought to capture the city to secure the flank of his troops advancing toward the rich oil fields of the Caucasus and to cut off the fundamental transport routes of the Soviet Union along the Volga River.
4	Lo que siguió fue una brutal guerra de desgaste que terminó por quebrantar definitivamente el poderío militar alemán.	1	What followed was a brutal war of attrition that ended up definitively breaking German military power.
5	La batalla se transformó rápidamente en una pesadilla sin precedentes de combate urbano.	2	The battle quickly transformed into an unprecedented nightmare of urban combat.
6	Tras los devastadores bombardeos de la Luftwaffe que redujeron la ciudad a escombros, las fuerzas alemanas entraron en Stalingrado, donde se toparan con una resistencia soviética encarnizada.	2	Following the devastating bombings by the Luftwaffe that reduced the city to rubble, German forces entered Stalingrad, where they encountered fierce Soviet resistance.
7	Los combates se libraban a corta distancia dentro de fábricas destruidas, sótanos y edificios residenciales, un estilo de lucha que los alemanes denominaron "guerra de ratas".	2	The fighting was waged at close range inside destroyed factories, basements, and residential buildings, a style of fighting that the Germans called "rat war".
8	A pesar de la superioridad técnica y táctica inicial de los invasores, el Ejército Rojo aprovechó el paisaje en ruinas para neutralizar esas ventajas, disputando cada cuadra y cada estructura a un costo humano incalculable para ambos bandos.	2	Despite the initial technical and tactical superiority of the invaders, the Red Army took advantage of the ruined landscape to neutralize those advantages, contesting every block and every structure at an incalculable human cost for both sides.
9	El momento culminante del enfrentamiento llegó en noviembre de 1942 con la ejecución de la Operación Urano, una brillante contraofensiva soviética.	3	The culminating moment of the confrontation came in November 1942 with the execution of Operation Uranus, a brilliant Soviet offensive.
10	Al percatarse de que los flancos alemanes estaban protegidos por ejércitos aliados de Rumanía y Hungría, mal equipados y desgastados, el Ejército Rojo lanzó un ataque masivo en dos frentes.	3	Upon realizing that the German flanks were protected by allied armies from Romania and Hungary, which were poorly equipped and worn out, the Red Army launched a massive attack on two fronts.
11	Esta maniobra envolvente logró romper las líneas débiles y cercar por completo al Sexto Ejército alemán dentro de Stalingrado.	3	This encircling maneuver managed to break through the weak lines and completely surround the German Sixth Army inside Stalingrad.
12	Hitler prohibió rotundamente cualquier intento de retirada y ordenó a sus tropas resistir a toda costa, prometiendo un reabastecimiento aéreo que nunca llegó a materializarse de forma suficiente.	3	Hitler flatly forbade any attempt at retreat and ordered his troops to resist at all costs, promising an aerial resupply that never materialized sufficiently.
13	Atrapadas sin alimentos, uniformes de invierno ni municiones adecuadas, las fuerzas del Eje sufrieron los efectos de la inanición y las temperaturas polares a medida que avanzaba el implacable invierno ruso.	4	Trapped without food, winter uniforms, or adequate ammunition, the Axis forces suffered the effects of starvation and polar temperatures as the relentless Russian winter advanced.
14	A principios de 1943, las fuerzas soviéticas redujeron sistemáticamente el reducto de resistencia, obligando al mariscal de campo Friedrich Paulus a firmar la capitulación de los restos de su ejército el 2 de febrero de 1943.	4	In early 1943, Soviet forces systematically reduced the pocket of resistance, forcing Field Marshal Friedrich Paulus to sign the capitulation of the remnants of his army on February 2, 1943.
15	Esta catastrófica derrota se saldó con más de dos millones de bajas totales, sepultó definitivamente el mito de la invencibilidad nazi y obligó a Alemania a emprender una retirada estratégica permanente de la que jamás lograría recuperarse.	4	This catastrophic defeat resulted in over two million total casualties, definitively buried the myth of Nazi invincibility, and forced Germany to undertake a permanent strategic retreat from which it would never recover.`;

